services:
  postgres:
    image: postgres:16-alpine
    container_name: fluxocaixa-db
    environment:
      POSTGRES_DB: fluxocaixa
      POSTGRES_USER: fluxocaixa_user
      POSTGRES_PASSWORD: fluxocaixa_pass
    ports:
      - "5432:5432"
    volumes:
      - fluxocaixa_pgdata:/var/lib/postgresql/data

volumes:
  fluxocaixa_pgdata: