spring.application.name=fluxocaixa

# Conexao com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/fluxocaixa
spring.datasource.username=fluxocaixa_user
spring.datasource.password=fluxocaixa_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate NAO deve criar/alterar tabelas -- isso e responsabilidade do Flyway
spring.jpa.hibernate.ddl-auto=validate

# Mostra o SQL executado no console (util para aprender/debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration